### PR TITLE
created folders for infographics products of the data teams

### PR DESCRIPTION
**Pull request by elashahar01**

### CODE REVIEW

**Review by baruchpicard — APPROVED** [review]

**Review by baruchpicard — APPROVED** [review]

**Comment by atalyaalon** [comment]
@elashahar01 why splitting the infographics suggestions and use cases?
Why not have per use case the relevant code and the infographics suggestions in it's directory?

**Comment by Mano3** [comment]
I disagree with Atalya, every infographic suggestion might rise from investigating an use case, but it should be generic for any other relevant use cases.

**Comment by elashahar01** [comment]
@atalyaalon As Mano wrote, suggestions don't have to be directly related to use case investigations. Furthermore, I believe that this separation will encourage creating clear documentation for FE volunteers.

**Comment by atalyaalon** [comment]
@elashahar01 @Mano3 ok, thanks! Approving

**Review by atalyaalon — APPROVED** [review]

**Pull request merged**
